"""empty message

Revision ID: 00a5d633fd8c
Revises: 84c85cbb34b9
Create Date: 2019-01-12 20:25:08.129754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a5d633fd8c'
down_revision = '84c85cbb34b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_building', table_name='location')
    op.create_index(op.f('ix_location_building'), 'location', ['building'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_building'), table_name='location')
    op.create_index('ix_location_building', 'location', ['building'], unique=1)
    # ### end Alembic commands ###
