"""location table

Revision ID: 495e42f2b6ea
Revises: ac707d1bd1f3
Create Date: 2018-12-18 15:10:12.898161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495e42f2b6ea'
down_revision = 'ac707d1bd1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('building', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_building'), 'location', ['building'], unique=True)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_building'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
