"""empty message

Revision ID: 84c85cbb34b9
Revises: 76f9d5a8ac65
Create Date: 2019-01-10 20:45:24.533581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c85cbb34b9'
down_revision = '76f9d5a8ac65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=254), nullable=True),
    sa.Column('description', sa.String(length=254), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_key'), 'key', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_key'), table_name='key')
    op.drop_table('key')
    # ### end Alembic commands ###
